apiVersion: v1
kind: Service
metadata:
  name: cortexai
  namespace: cortexai  # FIX #10
  labels:
    app: cortexai
spec:
  type: ClusterIP
  selector:
    app: cortexai
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
